### ISSUE TITLE
assets/wp-purge-pagespeed-button.min.js 404 when SCRIPT_DEBUG is defined and true

### ISSUE THREAD

**Issue by AlexeyDemidov** [salaros/wp-purge-pagespeed-button#4]
The function `embed_admin_assets()` has a bug that if `SCRIPT_DEBUG` is defined and `true` then  `wp_enqueue_script` is called with `wp-purge-pagespeed-button.min.js` which doesn't exist in the plugin zip archive downloadable from wordpress.org.

**Comment by salaros** [comment]
Yeah, indeed it was a bug. I've fixed it in 10.0.5. Please update it and let me know if it worked for you

**Comment by salaros** [comment]
@AlexeyDemidov, hi there, so have you managed to check the new version out?
